sudo: false
dist: trusty

addons:
  apt:
    packages:
      - oracle-java8-installer

language: java

# env:
# -
jdk:
  - oraclejdk8

script: mvn clean verify

after_success:
  - mvn clean test jacoco:report coveralls:report
